[build]
command = "hugo -s exampleSite -d ../public --themesDir ../../"
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.37.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.37.1"